DATE_COLUMN = "Date"
LABEL_COLUMN = "Labels"
TYPE_COLUMN = "Type"
AMOUNT_COLUMN = "Amount"
WALLET_COLUMN = "Wallet"
CATEGORY_COLUMN = "Category"
BALANCE_COLUMN = "Balance"

ALL_COLUMNS = {
    DATE_COLUMN,
    LABEL_COLUMN,
    TYPE_COLUMN,
    AMOUNT_COLUMN,
    WALLET_COLUMN,
    CATEGORY_COLUMN,
}
