DUO_DEBT_WALLET = "DUO Schuld"
WBW_SISTER = "WBW (Broertje en Zusjelief)"
WBW_FRIENDS = "WBW (The Ridiculous Seven)"
WBW_DISPUUT = "WBW (Alea Iacta Est)"
CASH_WALLET = "Cash"
ING_WALLET = "ING"
KOOPZEGEL_WALLET = "Koopzegel"
REVOLUT_WALLET = "Revolut"
ASN_WALLET = "ASN"
FIXED_CHARGES_WALLET = "ASN Vaste lasten"
EXPECTED_TAXES_WALLET = "Expected taxes"
DEBIT_WALLET = "Debit"
DUO_INVEST_WALLET = "ASN Beleggen (DUO)"
SPLIT_WALLET = "Uitsplitsen"
INVEST_WALLET = "ASN Beleggen (Persoonlijk)"
CRYPTO_WALLET = "Crypto"
SAVINGS_WALLET = "ASN Spaarrekening"

WALLET_MAPPING = {
    SAVINGS_WALLET: [ING_WALLET],
    DUO_DEBT_WALLET: [DUO_INVEST_WALLET],
    DEBIT_WALLET: [WBW_SISTER, WBW_FRIENDS, WBW_DISPUUT, KOOPZEGEL_WALLET],
    ASN_WALLET: [
        CASH_WALLET,
        SPLIT_WALLET,
        REVOLUT_WALLET,
        FIXED_CHARGES_WALLET,
        EXPECTED_TAXES_WALLET,
    ],
}

INITIAL_BALANCES = {
    DUO_DEBT_WALLET: -25964.87,
    WBW_SISTER: 354.94,
    WBW_FRIENDS: -5.73,
    WBW_DISPUUT: 10.44,
    CASH_WALLET: 20,
    ING_WALLET: 14119.12,
    KOOPZEGEL_WALLET: 265.6,
    REVOLUT_WALLET: 179.75,
    ASN_WALLET: 0,
    FIXED_CHARGES_WALLET: 0,
    EXPECTED_TAXES_WALLET: -596.02,
    DEBIT_WALLET: 0,
    DUO_INVEST_WALLET: 8785,
    SPLIT_WALLET: 0,
    INVEST_WALLET: 6038,
    CRYPTO_WALLET: 1222.85,
    SAVINGS_WALLET: 0,
}

ALL_WALLETS = set(INITIAL_BALANCES.keys())
